repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
<<<<<<< HEAD
    rev: v5.0.0
=======
    rev: v6.0.0
>>>>>>> upstream/main
    hooks:
    -   id: check-ast
    -   id: check-added-large-files
        args: ['--maxkb=25000']
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: no-commit-to-branch
        args: ['--branch', 'main']

-   repo: https://github.com/asottile/pyupgrade
<<<<<<< HEAD
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
=======
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
>>>>>>> upstream/main
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
