seed: ${SEED}

### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: ${ADAPTER}
trust_remote_code: true
flash_attn: auto
use_cache: false

### method
stage: sft
do_train: false
finetuning_type: lora
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target: k_proj,v_proj,down_proj

### dataset
eval_dataset: ${DATASET}
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
packing: false

### output
output_dir: ${OUTPUT_DIR}
logging_steps: 5
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
plot_loss: true
include_num_input_tokens_seen: true
save_total_limit: 1

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
max_steps: 40000
weight_decay: 1.0e-5
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
max_grad_norm: 1.0
optim: adamw_torch
report_to:
- wandb

### eval
do_eval: false
per_device_eval_batch_size: 4

### predict
do_predict: true
predict_with_generate: true
temperature: null
top_k: null
top_p: null
do_sample: false
