seed: ${SEED}

### model
model_name_or_path: llama-3-8b-instruct
adapter_name_or_path: ${ADAPTER}
trust_remote_code: true
flash_attn: auto
use_cache: false

### method
stage: sft
do_train: false
finetuning_type: prompt-tuning
task_type: CAUSAL_LM
num_virtual_tokens: 100

### dataset
eval_dataset: ${DATASET}
template: llama3
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
packing: false

### output
output_dir: ${OUTPUT_DIR}
logging_steps: 5
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
plot_loss: true
include_num_input_tokens_seen: true
push_to_hub: true
push_to_hub_organization: rbelanec
load_best_model_at_end: true
save_total_limit: 1

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 3.0e-1
max_steps: 40000
weight_decay: 1.0e-5
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
max_grad_norm: 1.0
optim: adamw_torch
report_to:
- wandb

### eval
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 200
val_size: 0.1

### predict
do_predict: true
predict_with_generate: true
