### model
model_name_or_path: google/gemma-3-1b-it
trust_remote_code: true
flash_attn: auto
use_cache: false

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target: k_proj,v_proj,down_proj

### dataset
dataset: mnli
template: gemma
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
packing: false

### output
output_dir: saves/Gemma-3-1B-Instruct/lora/train_2025-04-09-17-42-00
logging_steps: 5
save_steps: 0.1
plot_loss: true
overwrite_output_dir: true
save_only_model: false
plot_loss: true
include_num_input_tokens_seen: true
push_to_hub: true
push_to_hub_organization: rbelanec
load_best_model_at_end: true
metric_for_best_model: eval_mnli_eval_loss
save_total_limit: 1

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
max_steps: 20000
weight_decay: 1.0e-5
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
max_grad_norm: 1.0
optim: adamw_torch
report_to:
- wandb

### eval
eval_dataset: mnli_eval
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 0.1

### predict
# do_predict: true
# predict_with_generate: true
